package com.bancosantander.likeu.model;

/**
 * This class was automatically generated by the data modeler tool.
 */
public class CardDetail implements java.io.Serializable {
/** 
@param
*/
	private static final long serialVersionUID = 1L;

	private com.bancosantander.likeu.model.AllOfCardDetailPeriod period;
	private java.lang.String type;
	private com.bancosantander.likeu.model.AllOfCardDetailCurrentLimit current_limit;
	private java.lang.String display_number;
	private com.bancosantander.likeu.model.AllOfCardDetailLowerLimit lower_limit;
	private com.bancosantander.likeu.model.AllOfCardDetailNextIncrease next_increase;
	private com.bancosantander.likeu.model.AllOfCardDetailPotentialLimit potential_limit;

/**
 * Detalle de tarjetas
 */
	public CardDetail() {
	}
/**
 * Constructor de la clase
 * @param      period    array that is the source of characters.
 * @param      type    array that is the source of characters.
 * @param      current_limit    array that is the source of characters.
 * @param      display_number    array that is the source of characters.
 * @param      lower_limit    array that is the source of characters.
 * @param      next_increase    array that is the source of characters.
 * @param      potential_limit    array that is the source of characters.
 * @exception  IndexOutOfBoundsException  if the <code>offset</code>
 */
	public CardDetail(
		com.bancosantander.likeu.model.AllOfCardDetailPeriod period,
		java.lang.String type,
		com.bancosantander.likeu.model.AllOfCardDetailCurrentLimit current_limit,
		java.lang.String display_number,
		com.bancosantander.likeu.model.AllOfCardDetailLowerLimit lower_limit,
		com.bancosantander.likeu.model.AllOfCardDetailNextIncrease next_increase,
		com.bancosantander.likeu.model.AllOfCardDetailPotentialLimit potential_limit) {
	this.period = period;
	this.type = type;
	this.current_limit = current_limit;
	this.display_number = display_number;
	this.lower_limit = lower_limit;
	this.next_increase = next_increase;
	this.potential_limit = potential_limit;
}
	/**
	 * @return
	 */	
	public com.bancosantander.likeu.model.AllOfCardDetailPeriod getPeriod() {
		return this.period;
	}
	/** 
	 * @param com.bancosantander.likeu.model.AllOfCardDetailPeriod
	 */
	public void setPeriod(
			com.bancosantander.likeu.model.AllOfCardDetailPeriod period) {
		this.period = period;
	}
	/**
	 * @return
	 */	
	public java.lang.String getType() {
		return this.type;
	}
	/** 
	 * @param String
	 */
	public void setType(java.lang.String type) {
		this.type = type;
	}
	/**
	 * @return
	 */	
	public com.bancosantander.likeu.model.AllOfCardDetailCurrentLimit getCurrent_limit() {
		return this.current_limit;
	}
	/** 
	 * @param com.bancosantander.likeu.model.AllOfCardDetailCurrentLimit
	 */
	public void setCurrent_limit(
			com.bancosantander.likeu.model.AllOfCardDetailCurrentLimit current_limit) {
		this.current_limit = current_limit;
	}
	/**
	 * @return
	 */	
	public java.lang.String getDisplay_number() {
		return this.display_number;
	}
	/** 
	 * @param String
	 */
	public void setDisplay_number(java.lang.String display_number) {
		this.display_number = display_number;
	}
	/**
	 * @return
	 */	
	public com.bancosantander.likeu.model.AllOfCardDetailLowerLimit getLower_limit() {
		return this.lower_limit;
	}
	/** 
	 * @param com.bancosantander.likeu.model.AllOfCardDetailLowerLimit
	 */
	public void setLower_limit(
			com.bancosantander.likeu.model.AllOfCardDetailLowerLimit lower_limit) {
		this.lower_limit = lower_limit;
	}
	/**
	 * @return
	 */	
	public com.bancosantander.likeu.model.AllOfCardDetailNextIncrease getNext_increase() {
		return this.next_increase;
	}
	/** 
	 * @param com.bancosantander.likeu.model.AllOfCardDetailNextIncrease
	 */
	public void setNext_increase(
			com.bancosantander.likeu.model.AllOfCardDetailNextIncrease next_increase) {
		this.next_increase = next_increase;
	}
	/**
	 * @return
	 */	
	public com.bancosantander.likeu.model.AllOfCardDetailPotentialLimit getPotential_limit() {
		return this.potential_limit;
	}
	/** 
	 * @param com.bancosantander.likeu.model.AllOfCardDetailPotentialLimit
	 */
	public void setPotential_limit(
			com.bancosantander.likeu.model.AllOfCardDetailPotentialLimit potential_limit) {
		this.potential_limit = potential_limit;
	}

}